ODC-7600: Add Timeout field in the start pipeline modal
openshift-pipelines/console-plugin pull request #123
Opened 2024-06-11 11:32 UTC by vikram-raj

Add a Timeout field in the start pipeline modal

https://github.com/openshift/console/assets/2561818/336610c9-ec87-44d6-8c18-c31a8e12ab94

2024-06-12 05:14 UTC, vikram-raj commented
/retest

2024-06-12 07:00 UTC, lokanandaprabhu requested changes
If I don't enter any value in timeout I am getting error message

<img width="983" alt="Screenshot 2024-06-12 at 12 10 30 PM" src="https://github.com/openshift-pipelines/console-plugin/assets/102503482/1ad32a91-5084-43f9-a1ba-50aa30ed2b54">

2024-06-12 07:00 UTC, lokanandaprabhu commented on src/components/start-pipeline/utils.ts
> +  console.log(timeouts, '####');
Can you please remove this log

2024-06-12 07:04 UTC, lokanandaprabhu commented
Due to new form group, the space is more above Timeouts section, can we add this as part of Parameter section or remove the additional space? 

<img width="1131" alt="Screenshot 2024-06-12 at 12 32 00 PM" src="https://github.com/openshift-pipelines/console-plugin/assets/102503482/857ac1be-32d1-4428-9b66-73ee3062754b">

2024-06-18 08:27 UTC, vikram-raj commented
> Due to new form group, the space is more above Timeouts section, can we add this as part of Parameter section or remove the additional space?

I added it in a different section as it is not a part of the parameters. Timeout is a different section.

2024-06-18 09:43 UTC, lokanandaprabhu approved these changes

2024-06-18 09:43 UTC, lokanandaprabhu commented
/lgtm

2024-06-18 09:48 UTC, merged